### ISSUE TITLE
Search fields set to meta only

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress-Admin#12]
Is there a reason for this? May be non-intuitive for users for the search not to include post_title and post_content. I'd be glad to submit a PR.

**Comment by tinkerborg** [comment]
It's because EP doesn't add the post_title, post_content and post_excerpt fields by default unless search_fields is empty. Should be fixed in this PR: https://github.com/10up/ElasticPress-Admin/pull/13

**Comment by AaronHolbrook** [comment]
Thanks @psorensen and @tinkerborg - ElasticPress itself changed after I wrote this plugin initially.

I fixed this in #17 

Appreciate the heads up and contributions!
